### ISSUE TITLE
Bigger padding when the notification popup is not integrated

### ISSUE THREAD

**Issue by peixotofraga** [qwreey/quick-settings-tweaks#26]
When I turn the integrated popup off, the padding around quick setting gets larger. When I turn it back on, this weird border appears. Perhaps this is not caused only by the extension (it may also be the theme's fault), but it seems worth investigating.
![Screenshot from 2022-11-04 17-53-57](https://user-images.githubusercontent.com/21206861/200075148-d86bb1af-bc29-4a23-9a61-91ff632ef99c.png)
![Screenshot from 2022-11-04 17-53-13](https://user-images.githubusercontent.com/21206861/200075152-3ebb6b54-1d7f-48f7-86cc-08819a804dac.png)
![Screenshot from 2022-11-04 18-11-47](https://user-images.githubusercontent.com/21206861/200075498-cd6f33f7-5a30-49ab-b2f3-8f53449357f5.png)

**Comment by qwreey75** [comment]
Fixed in Refactored version! New version will be published in this weekend!

**Comment by IOplus** [comment]
I'm on the latest version (1.15) that was released recently, and this is still not fixed.

**Comment by qwreey** [comment]
Separated layout removed in 2.1 due to instability, it requires re-layouting hacky
